// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("Major Code Smell", "S125:Sections of code should not be commented out", Justification = "<Oczekujące>", Scope = "member", Target = "~M:AverageExchangeRatesAnalyzer.Helpers.Excel.CustomCellFormats.GetCustomCellFormats(System.UInt32)~DocumentFormat.OpenXml.Spreadsheet.CellFormats")]
[assembly: SuppressMessage("Minor Code Smell", "S3220:Method calls should not resolve ambiguously to overloads with \"params\"", Justification = "<Oczekujące>", Scope = "member", Target = "~M:AverageExchangeRatesAnalyzer.Helpers.Excel.ExcelExporterHelper.CreateStyleSheet~DocumentFormat.OpenXml.Spreadsheet.Stylesheet")]
[assembly: SuppressMessage("Minor Code Smell", "S3220:Method calls should not resolve ambiguously to overloads with \"params\"", Justification = "<Oczekujące>", Scope = "member", Target = "~M:AverageExchangeRatesAnalyzer.Helpers.Excel.CustomCellFormats.GetCustomCellFormats(System.UInt32)~DocumentFormat.OpenXml.Spreadsheet.CellFormats")]
[assembly: SuppressMessage("Major Code Smell", "S2629:Logging templates should be constant", Justification = "<Oczekujące>", Scope = "member", Target = "~M:AverageExchangeRatesAnalyzer.FileOperations.FileManagement.ReportFileCleaner.Removereports(System.String,System.String,System.Boolean,System.Boolean,Microsoft.Extensions.Logging.ILogger)")]
[assembly: SuppressMessage("StyleCop.CSharp.OrderingRules", "SA1200:Using directives should be placed correctly", Justification = "<Oczekujące>")]
[assembly: SuppressMessage("Minor Code Smell", "S1075:URIs should not be hardcoded", Justification = "<Oczekujące>", Scope = "member", Target = "~F:AverageExchangeRatesAnalyzer.DataAccess.HttpNbpApiClient.UriString")]
[assembly: SuppressMessage("Minor Code Smell", "S3220:Method calls should not resolve ambiguously to overloads with \"params\"", Justification = "<Oczekujące>", Scope = "member", Target = "~M:AverageExchangeRatesAnalyzer.FileOperations.Exporters.ExcelExporter.PrepareDataAndExport(System.Collections.Generic.List{AverageExchangeRatesAnalyzer.DataObjects.ExchangeRatesTable},System.Collections.Generic.List{System.String})")]
[assembly: SuppressMessage("Minor Code Smell", "S3220:Method calls should not resolve ambiguously to overloads with \"params\"", Justification = "<Oczekujące>", Scope = "member", Target = "~M:AverageExchangeRatesAnalyzer.Helpers.Excel.CustomFills.GetCustomFills~DocumentFormat.OpenXml.Spreadsheet.Fills")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1633:File should have header", Justification = "<Oczekujące>")]
[assembly: SuppressMessage("Minor Code Smell", "S6667:Logging in a catch clause should pass the caught exception as a parameter.", Justification = "<Oczekujące>", Scope = "member", Target = "~M:AverageExchangeRatesAnalyzer.FileOperations.Exporters.ExcelExporter.PrepareDataAndExport(System.Collections.Generic.List{AverageExchangeRatesAnalyzer.DataObjects.ExchangeRatesTable},System.Collections.Generic.List{System.String})")]
[assembly: SuppressMessage("StyleCop.CSharp.ReadabilityRules", "SA1414:Tuple types in signatures should have element names", Justification = "<Oczekujące>", Scope = "member", Target = "~M:AverageExchangeRatesAnalyzer.DataAccess.HttpNbpApiClient.GetExchangeRates(System.String,System.String)~System.Threading.Tasks.Task{System.ValueTuple{System.Collections.Generic.List{AverageExchangeRatesAnalyzer.DataObjects.ExchangeRatesTable},System.String}}")]
[assembly: SuppressMessage("Minor Code Smell", "S3267:Loops should be simplified with \"LINQ\" expressions", Justification = "<Oczekujące>", Scope = "member", Target = "~M:AverageExchangeRatesAnalyzer.FileOperations.Exporters.ExcelExporter.FillDayOffColumn(System.DateTime,System.Collections.Generic.Dictionary{System.String,AverageExchangeRatesAnalyzer.Helpers.Excel.CustomRow},System.Collections.Generic.List{System.String})")]
[assembly: SuppressMessage("Minor Code Smell", "S3220:Method calls should not resolve ambiguously to overloads with \"params\"", Justification = "<Oczekujące>", Scope = "member", Target = "~M:AverageExchangeRatesAnalyzer.Helpers.Excel.ExcelExporterHelper.AutoSizeCells(DocumentFormat.OpenXml.Spreadsheet.SheetData)~DocumentFormat.OpenXml.Spreadsheet.Columns")]
[assembly: SuppressMessage("Minor Code Smell", "S6667:Logging in a catch clause should pass the caught exception as a parameter.", Justification = "<Oczekujące>", Scope = "member", Target = "~M:AverageExchangeRatesAnalyzer.FileOperations.FileManagement.ReportFileManager.PerformManagementOfNewReport")]
[assembly: SuppressMessage("Minor Code Smell", "S6667:Logging in a catch clause should pass the caught exception as a parameter.", Justification = "<Oczekujące>", Scope = "member", Target = "~M:AverageExchangeRatesAnalyzer.FileOperations.FileManagement.ReportFileCleaner.Removereports(System.String,System.String,System.Boolean,System.Boolean,Microsoft.Extensions.Logging.ILogger)")]
